modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/shBLOCK/IntegratedProxy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated_proxy"
logoFile="icon.png"
authors="shBLOCK"

[[mods]]
modId="integratedproxy"
version="${file.jarVersion}"
displayName="IntegratedProxy"
description='''
An addon for Integrated Dynamics that allows you to redirect the part's target to another position.
'''
[[dependencies.integrated_proxy]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrated_proxy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrated_proxy]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrated_proxy]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.8.0,)"
    ordering="NONE"
    side="BOTH"
